# Generated by Django 4.1.5 on 2023-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
