[tool.poetry]
name = "dev-site"
version = "0.1.0"
description = "Dev site for Django Admin Omni Search"
authors = ["Pavel Žák <pavel@zak.global>"]
license = "MIT"
readme = "README.md"
packages = [{include = "dev_site"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
