[tool.poetry]
name = "django-omni-search"
version = "0.1.0"
description = "Quick search anything in Django Admin from a single place"
authors = ["Pavel Žák <pavel@zak.global>"]
license = "MIT"
readme = "README.md"
packages = [{include = "django_omni_search"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
